import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { afterAll, afterEach, beforeEach, describe, expect, it } from 'vitest';

import { createRepoTemplate, createTempRepo, type TempRepo } from '@orcaops/test-harness';

import { makeAgent } from '../support/test-agent.js';

describe('orcaops update --force byte-stability', () => {
  let repo: TempRepo;
  let agent: ReturnType<typeof makeAgent>;

  // `init` is identical for every test here and costs ~450ms; run it once
  // and give each test a ~20ms copy of the result.
  const repoTemplate = createRepoTemplate(
    async (repoPath) => {
      await makeAgent({ cwd: repoPath }).runRaw([
        'init',
        '--scope',
        'project',
        '--no-llm',
        '--agents-md',
      ]);
    },
    { initialBranch: 'main' }
  );

  beforeEach(async () => {
    repo = await repoTemplate.checkout();
    agent = makeAgent({ cwd: repo.path });
  });

  afterAll(async () => {
    await repoTemplate.destroy();
  });

  afterEach(async () => {
    await repo.cleanup();
  });

  it('repeated update --force produces byte-identical AGENTS.md / CLAUDE.md', async () => {
    // After init, both bootstrap files exist. Run update --force three
    // times and snapshot the bytes after each. The body must be
    // identical across all three runs — otherwise every CI invocation
    // shows whitespace drift even though nothing actually changed.
    //
    // The failure this pins: a single blank line removed on update --force
    // after a template change. Byte-stability is locked in tests so future
    // template / generator work doesn't reintroduce nondeterminism.
    const agentsPath = path.join(repo.path, 'AGENTS.md');
    const claudePath = path.join(repo.path, 'CLAUDE.md');

    const r1 = await agent.runRaw(['update', '--force']);
    expect(r1.exitCode).toBe(0);
    const agents1 = await readFile(agentsPath, 'utf8');
    const claude1 = await readFile(claudePath, 'utf8');

    const r2 = await agent.runRaw(['update', '--force']);
    expect(r2.exitCode).toBe(0);
    const agents2 = await readFile(agentsPath, 'utf8');
    const claude2 = await readFile(claudePath, 'utf8');

    const r3 = await agent.runRaw(['update', '--force']);
    expect(r3.exitCode).toBe(0);
    const agents3 = await readFile(agentsPath, 'utf8');
    const claude3 = await readFile(claudePath, 'utf8');

    expect(agents2).toBe(agents1);
    expect(agents3).toBe(agents1);
    expect(claude2).toBe(claude1);
    expect(claude3).toBe(claude1);
  });

  it('plain update refreshes a skill whose fingerprint differs at the same version', async () => {
    // The same-version refresh gap: a
    // template body edit shipped WITHOUT a version bump must reach installed
    // trees through plain `orcaops update`. Simulate a file generated by an
    // older body at the same version: same generatedBy, different recorded
    // contentHash fingerprint.
    const skillPath = path.join(repo.path, '.claude/skills/orcaops-capture/SKILL.md');
    const pristine = await readFile(skillPath, 'utf8');
    expect(pristine).toMatch(/contentHash: "[0-9a-f]{12}"/);
    await writeFile(
      skillPath,
      pristine.replace(/contentHash: "[0-9a-f]+"/, 'contentHash: "000000000000"'),
      'utf8'
    );

    const r = await agent.runRaw(['update']);
    expect(r.exitCode).toBe(0);
    expect(await readFile(skillPath, 'utf8')).toBe(pristine);
  });

  it('plain update leaves a user-edited file alone when the template is unchanged', async () => {
    const skillPath = path.join(repo.path, '.claude/skills/orcaops-capture/SKILL.md');
    const pristine = await readFile(skillPath, 'utf8');
    const edited = pristine + '\n# CUSTOM USER ADDITION\n';
    await writeFile(skillPath, edited, 'utf8');

    const r = await agent.runRaw(['update']);
    expect(r.exitCode).toBe(0);
    // Same generation stamp (version + fingerprint) → the edit is respected.
    expect(await readFile(skillPath, 'utf8')).toBe(edited);
  });

  it('update --force is byte-stable when surrounded by user content', async () => {
    // Wrap the managed section in user content, then assert that
    // repeated --force runs preserve every byte (including the slice
    // math around the marker boundaries).
    const agentsPath = path.join(repo.path, 'AGENTS.md');
    const original = await readFile(agentsPath, 'utf8');
    const wrapped = `# Project\n\nuser line above\n\n${original}\nfooter line below\n`;
    await writeFile(agentsPath, wrapped, 'utf8');

    await agent.runRaw(['update', '--force']);
    const first = await readFile(agentsPath, 'utf8');
    await agent.runRaw(['update', '--force']);
    const second = await readFile(agentsPath, 'utf8');

    expect(second).toBe(first);
    expect(first.startsWith('# Project\n\nuser line above\n\n')).toBe(true);
    expect(first.endsWith('footer line below\n')).toBe(true);
  });
});

describe('ahead guard (older CLI vs newer-generation install)', () => {
  let repo: TempRepo;
  let agent: ReturnType<typeof makeAgent>;

  beforeEach(async () => {
    repo = await createTempRepo({ initialBranch: 'main' });
    agent = makeAgent({ cwd: repo.path });
    await agent.init({ noLlm: true, scope: 'project', agentsMd: true });
  });

  afterEach(async () => {
    await repo.cleanup();
  });

  /** Restamp a generated file as if written by a much newer orcaops. */
  async function restampAhead(rel: string): Promise<string> {
    const abs = path.join(repo.path, rel);
    const ahead = (await readFile(abs, 'utf8')).replace(/orcaops@[^"\n]+/, 'orcaops@99.0.0');
    await writeFile(abs, ahead, 'utf8');
    return ahead;
  }

  it('plain update preserves an ahead skill, exits 0, warns, and carries preserved_ahead in JSON', async () => {
    const rel = '.claude/skills/orcaops-capture/SKILL.md';
    const aheadBytes = await restampAhead(rel);

    const res = await agent.runRaw(['update', '--json']);
    expect(res.exitCode).toBe(0);
    expect(await readFile(path.join(repo.path, rel), 'utf8')).toBe(aheadBytes);

    const out = JSON.parse(res.stdout);
    expect(out.refreshed).not.toContain(rel);
    expect(out.preserved_ahead).toEqual([{ path: rel, stamped_version: '99.0.0' }]);
    expect(out.warnings.join('\n')).toMatch(/NEWER orcaops/);
    expect(out.warnings.join('\n')).toMatch(/upgrade orcaops/i);
  });

  it('update --force DOWNGRADES the ahead skill — proving the guard, not luck, preserves it', async () => {
    const rel = '.claude/skills/orcaops-capture/SKILL.md';
    await restampAhead(rel);

    const res = await agent.runRaw(['update', '--force', '--json']);
    expect(res.exitCode).toBe(0);
    const out = JSON.parse(res.stdout);
    expect(out.preserved_ahead).toEqual([]);
    expect(out.warnings.join('\n')).toMatch(/--force overwrote/);
    expect(await readFile(path.join(repo.path, rel), 'utf8')).not.toMatch(/orcaops@99\.0\.0/);
  });

  it('plain update preserves an ahead instruction block, surfaced via preserved_ahead', async () => {
    const agentsPath = path.join(repo.path, 'AGENTS.md');
    const ahead = (await readFile(agentsPath, 'utf8')).replace(
      /orcaops:start v=[^\s]+/,
      'orcaops:start v=99.0.0'
    );
    await writeFile(agentsPath, ahead, 'utf8');

    const res = await agent.runRaw(['update', '--json']);
    expect(res.exitCode).toBe(0);
    expect(await readFile(agentsPath, 'utf8')).toBe(ahead);

    const out = JSON.parse(res.stdout);
    const entry = out.agents_md.find((m: { path: string }) => m.path === 'AGENTS.md');
    // agents_md keeps its frozen {path, action} shape; divergence detail
    // travels only in preserved_ahead.
    expect(entry).toEqual({ path: 'AGENTS.md', action: 'unchanged' });
    expect(out.preserved_ahead).toContainEqual({ path: 'AGENTS.md', stamped_version: '99.0.0' });
  });
});
