import path from 'node:path';

import { getAgentOverlay } from '../overlay.js';
import { DEFAULT_PREFIX } from '../refs.js';
import { stampedDocument } from '../renderers.js';

/**
 * The generated OpenCode session plugin — the one `plugin-file` session-hook
 * surface (BETA). OpenCode has no declarative hook config; any `.js` file in
 * the project plugin dir auto-loads, so this wholly orcaops-owned generated
 * file self-registers by existing and rides the normal generated-file
 * pipeline (stamp, manifest, hash-guarded prune, uninstall, drift) with zero
 * new machinery — unlike the co-owned settings files the CLI's session-hook
 * planner merges into.
 *
 * Injection path: a one-shot `chat.message` handler keyed
 * on session id — it is in the published plugin types. Not used:
 * `experimental.chat.system.transform` (absent from published types; plugins
 * registering unknown keys are silently discarded on some versions) and
 * `session.created` + SDK prompt (creates a visible synthetic turn). The
 * known `chat.message` TUI display quirk is the accepted beta risk; the
 * fallback is `opencode.json` `"instructions": [...]` pointing at an
 * orcaops-owned static file.
 *
 * The stamp is a JS block comment matching the SAME regexes as markdown
 * artifacts (`generatedBy:` + two-space-indented `contentHash:`), so
 * extractStamp/classifyGeneratedFile work on it unchanged.
 */

/** Repo-relative plugin path, e.g. `.opencode/plugins/orcaops-session-context.js`. */
export function opencodeSessionPluginPath(prefix: string = DEFAULT_PREFIX): string {
  const pluginDir = getAgentOverlay('opencode')?.sessionHooks?.path ?? '.opencode/plugins';
  return path.join(pluginDir, `${prefix}-session-context.js`);
}

export function renderOpencodeSessionPlugin(opts: { generatedBy: string }): string {
  const body = `// orcaops session-start context (BETA). Generated by \`orcaops init\`;
// refreshed by \`orcaops update\`; removed by \`orcaops update --no-session-hooks\`
// or \`orcaops uninstall\`. Do not edit — edits are preserved but mark the file
// user-owned, and it will no longer be refreshed.
//
// Injects state-aware orcaops capture guidance ONCE per session by shelling
// out to \`orcaops hook session-start\` (always-exit-0 contract: silent when
// orcaops is not installed or the repo is uninitialized — never breaks the
// session).
const seenSessions = new Set();

export const OrcaopsSessionContext = async ({ $ } = {}) => ({
  'chat.message': async (_input, output) => {
    try {
      const sessionId = output?.message?.sessionID;
      if (!sessionId || seenSessions.has(sessionId)) return;
      seenSessions.add(sessionId);
      const result = await $\`orcaops hook session-start --agent opencode\`.quiet().nothrow();
      const text = (result?.stdout ?? '').toString().trim();
      if (!text || !Array.isArray(output?.parts)) return;
      // The part schema requires id/sessionID/messageID (opencode >= 1.18
      // rejects the WHOLE user message on a malformed part — worse than no
      // guidance). Source both ids from the message being augmented and skip
      // entirely when either is missing rather than risk the prompt.
      const messageId = output?.message?.id;
      if (!messageId || !sessionId) return;
      output.parts.push({
        id: \`prt_orcaops\${Date.now().toString(36)}\${Math.random().toString(36).slice(2, 10)}\`,
        sessionID: sessionId,
        messageID: messageId,
        type: 'text',
        text: \`<orcaops-session-context>\\n\${text}\\n</orcaops-session-context>\`,
      });
    } catch {
      // Best-effort by contract: guidance must never break a session.
    }
  },
});
`;
  return stampedDocument(`/* generatedBy: "orcaops@${opts.generatedBy}"`, ` */\n\n${body}`);
}
